version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/go/src/work
    depends_on:
      - db